name: "Create clusters"
on: [push]

jobs:
  clusterTest:
    strategy:
      matrix:
        cluster: [kind, k3s, minikube]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup K3S Cluster
        uses: nolar/setup-k3d-k3s@v1
        if: ${{ matrix.cluster == 'k3s' }}
        with:
          version: v1.25.4+k3s1  # E.g.: v1.21, v1.21.2, v1.21.2+k3s1
          metrics-enabled: false
          traefik-enabled: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Minikube Cluster
        if: ${{ matrix.cluster == 'minikube' }}
        uses: manusa/actions-setup-minikube@v2.7.1
        with:
          minikube version: 'v1.26.1'
          kubernetes version: 'v1.25.0'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Kind Cluster
        if: ${{ matrix.cluster == 'kind' }}
        uses: helm/kind-action@v1.4.0

      - name: Await cluster up and running
        uses: jupyterhub/action-k8s-await-workloads@v1
        with:
          workloads: "" # all
          namespace: "kube-system" # default
          timeout: 300
          max-restarts: 5

      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get namespace
          kubectl get pods --all-namespaces
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl cluster-info dump

      - name: Installing traefik
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update
          kubectl create namespace traefik
          helm install traefik traefik/traefik --namespace=traefik
